### ISSUE TITLE
CUDA environment problem

### ISSUE THREAD

**Issue by HeSongy** [zhangganlin/GlORIE-SLAM#11]
GPU GeForce GTX TITAN X
```
[INFO] Load droid pretrained checkpiont from ./pretrained/droid.pth!
[TRACKER] Tracking Triggered!
[INFO] Load ConvONet pretrained checkpiont from ./pretrained/middle_fine.pt!
[MAPPER] Mapping Triggered!
[TRACKER] :   1%|█▍                                                                                                                                           | 1/100 [00:01<01:45,  1.07s/it]Process Process-2:
Traceback (most recent call last):
  File "/home/cver/miniconda3/envs/glorie-slam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/cver/miniconda3/envs/glorie-slam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cver/code/GlORIE-SLAM/src/slam.py", line 93, in tracking
    self.tracker.run(self.stream)
  File "/home/cver/code/GlORIE-SLAM/src/tracker.py", line 54, in run
    self.motion_filter.track(timestamp, image, intrinsic)
  File "/home/cver/miniconda3/envs/glorie-slam/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/cver/miniconda3/envs/glorie-slam/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/cver/code/GlORIE-SLAM/src/motion_filter.py", line 79, in track
    corr = CorrBlock(self.fmap[None,[0]], gmap[None,[0]])(coords0)
  File "/home/cver/code/GlORIE-SLAM/src/modules/droid_net/corr.py", line 50, in __call__
    corr = CorrSampler.apply(self.corr_pyramid[i], coords/2**i, self.radius)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Thanks !

**Comment by zhangganlin** [comment]
I never met it before, are you using the same environment as [glorie_env ](https://github.com/zhangganlin/GlORIE-SLAM/blob/main/glorie_env.yaml)? 
Is the [droid_backends](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/setup.py#L8) compiled properly?

**Comment by zhangganlin** [comment]
Oh I might find the issue, you are using Titan X, which should use compute_52 according to this [blog](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/), adding 52 [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/setup.py#L21) and [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/setup.py#L51), then recompiling dorid_backends and lietorch might be helpful.

**Comment by HeSongy** [comment]
> Oh I might find the issue, you are using Titan X, which should use compute_52 according to this [blog](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/), adding 52 [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/setup.py#L21) and [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/setup.py#L51), then recompiling dorid_backends and lietorch might be helpful.

problem solved,Thanks!
